/*
 * This source file was generated by the Gradle 'init' task
 */
package javatest;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;

public class App {
    public String getGreeting()
    {
        return "Hello World!";
    }

    public static URL createUrl(String uriString) {
        try {
            URI uri = new URI(uriString);
            try{
                return uri.toURL();
            }
            catch(MalformedURLException e){
                System.out.println("An error occurred while converting to url: " + e.getMessage());
                return null;
            }
        } catch (URISyntaxException e) {
            System.out.println("An error occurred while creating uri: " + e.getMessage());
            return null;
        }
    }

    public static String readLine(BufferedReader reader){
        try {
            return reader.readLine();
        } catch (IOException e) {
            System.out.println("An error occurred while reading input: " + e.getMessage());
            return null;
        }
    }

    public static BufferedReader openStream(URL url){
        try {
            return new BufferedReader(new InputStreamReader(url.openStream()));
        } catch (IOException e) {
            System.out.println("An error occurred while opening stream: " + e.getMessage());
            return null;
        }
    }

    public static void main(String[] args)
    {
        String emailId = new String();
        System.out.flush();
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        while(emailId.length() < 1){
            System.out.println("Enter email: ");
            emailId = readLine(reader);
        }
        
        CharSequence seq = "@";
        if(emailId.contains(seq))
        {
            int count = 0;
            for(int i = 0; i < emailId.length(); i++){
                if(emailId.charAt(i) == '@'){
                    count++;
                    if(count > 1){
                        System.out.println("Invalid email, try again");
                        main(args);
                        return;
                    }
                }
            }

            emailId = emailId.split("@")[0];
        }

        String sitePrefix = "https://www.ecs.soton.ac.uk/people/";
        String website = sitePrefix + emailId;
        
        URL url = createUrl(website);

        boolean response = false;

        String nameLine = searchLines("property=\"og:title\" content=\"", url);
        if(nameLine != null){
            System.out.println("Name: " + printInfo(nameLine));
            response = true;
        }
        String title = searchLines("jobTitle\": \"", url);
        if(title != null){
            System.out.println("Title: " + printInfo(title));
            response = true;
        }

        String accepting = searchLines("Accepting applications from PhD students", url);
        if(accepting != null){
            System.out.println("They are accepting appilcations from PhD students");
        }

        String privateLine = searchLines("It only contains people who have explicitly given consent to appear in the public directory", url);
        if(privateLine != null){
            System.out.println("This person doesn't exist or isn't public in the directory");
            response = true;
        }

        if(!response) System.out.println("An unexpected error has occured");

        System.out.println("\n");
    }

    public static String printInfo(String line){
        if(line == null) return null;
        //System.out.println("AAH IT WORKED");
        int end = line.indexOf("\"");
        line = line.substring(0, end);
        return line;
    }

    //Returns the remainder of the first line that contains the desired string
    public static String searchLines(String nameProperty, URL url){
        BufferedReader urlReader = openStream(url);

        while(true){
            String line = "";
            try {
                line = urlReader.readLine();
            } catch (IOException e) {
                System.out.println("An error occurred while reading a line in the website: " + e.getMessage());
                break;
            }
            if(line == null) break;

            if(line.contains(nameProperty)){
                int index = line.indexOf(nameProperty) + nameProperty.length();
                return line.substring(index);
            }
        }
        return null;
    }
}
